name: Deploy Three Tier App to EKS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  FRONTEND_ECR_REPO: three-tier-frontend
  BACKEND_ECR_REPO: three-tier-backend

jobs:
  deploy:
    name: Build & Deploy to EKS
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout Code
    - name: Checkout Repository
      uses: actions/checkout@v4

    # 2️⃣ Configure AWS Credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # 3️⃣ Login to Amazon ECR
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # 4️⃣ Build & Push Frontend Image
    - name: Build & Push Frontend
      run: |
        docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$FRONTEND_ECR_REPO:latest ./frontend
        docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$FRONTEND_ECR_REPO:latest

    # 5️⃣ Build & Push Backend Image
    - name: Build & Push Backend
      run: |
        docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$BACKEND_ECR_REPO:latest ./backend
        docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$BACKEND_ECR_REPO:latest

    # 6️⃣ Update kubeconfig
    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME

    # 7️⃣ Deploy to Kubernetes
    - name: Deploy Kubernetes Manifests
      run: |
        kubectl apply -f Kubernetes-Manifests-file/Database/pv.yaml
        kubectl apply -f Kubernetes-Manifests-file/Database/pvc.yaml
        kubectl apply -f Kubernetes-Manifests-file/Database/secret.yaml
        kubectl apply -f Kubernetes-Manifests-file/Database/deployment.yaml
        kubectl apply -f Kubernetes-Manifests-file/Database/service.yaml
        kubectl apply -f Kubernetes-Manifests-file/Backend/deployment.yaml
        kubectl apply -f Kubernetes-Manifests-file/Backend/service.yaml
        kubectl apply -f Kubernetes-Manifests-file/Frontend/deployment.yaml
        kubectl apply -f Kubernetes-Manifests-file/Frontend/service.yaml
        kubectl apply -f ./ingress.yaml

    # 8️⃣ Verify Deployment
    - name: Verify Pods
      run: |
        kubectl get pods -n workshop
        kubectl get svc -n workshop
        kubectl get ingress -n workshop
